---
- name: Set Up Build Environment
  hosts: build-host
  become: yes
  tasks:
    - name: We need Java
      apt:
        name: default-jdk
        state: latest
    - name: We need git
      apt:
        name: git
        state: latest
    - name: We need maven
      apt:
        name: maven
        state: latest
    - name: Make dir for build
      file:
        path: /opt/build/boxfuse-sample-java-war-hello
        state: directory
        mode: '0755'

- name: Set Up FrontEnd Environment
  hosts: app
  become: yes
  tasks:
  - name: We need Tomcat
    apt:
      name: tomcat9
      state: latest
  - name: Ensure tomcat service is started
    service:
      name: tomcat9
      state: started

- name: Build an App
  hosts: build-host
  become: yes
  tasks:
    - name: Clone boxfuse repository
      git:
        clone: yes
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /opt/build/boxfuse-sample-java-war-hello
    - name: Build with maven
      command: mvn package
      args:
        chdir: /opt/build/boxfuse-sample-java-war-hello
    - name: Fetch build
      fetch:
        src: /opt/build/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /tmp/hello-1.0.war
        flat: yes

- name: Run an App
  hosts: app
  become: yes
  tasks:
  - name: Copy build
    copy:
      src: /tmp/hello-1.0.war
      dest: /usr/local/tomcat/webapps/
  - name: Restart tomcat
    service:
      name: tomcat9
      state: restarted
