---
- name: Run NGINX
  hosts: build-host
  become: yes
  tasks:
    - name: We need Nginx
      apt:
        name: nginx
        state: latest
- name: replace line
  replace:
    path: /var/www/html/index.nginx-debian.html
    regexp: '\<h1\>Welcome to nginx!\<\/h1\>'
    replace: '<p><script> document.write (new Date().toLocaleDateString()); </script></p>'
