---
- name: templating
  hosts: all
  become: yes
  
  var:
    source_folder: ./
    dest_folder: /var/www/html

  tasks:
    - name: We need Nginx
      apt:
        name: nginx
        state: latest
    - name: templ
      template: src={{ source_folder }}/index.j2 dest={{ dest_folder }}/index.html mode=0555